package backend.model;
// Generated Oct 6, 2023, 8:07:22 PM by Hibernate Tools 6.1.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Games generated by hbm2java
 */
public class Games implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer gid;
	private String name;
	private String year;
	@SuppressWarnings("rawtypes")
	private Set gamesOfUserses = new HashSet(0);
	@SuppressWarnings("rawtypes")
	private Set imageses = new HashSet(0);
	@SuppressWarnings("rawtypes")
	private Set postses = new HashSet(0);

	public Games() {
	}

	public Games(String name, String year) {
		this.name = name;
		this.year = year;
	}
	
	@SuppressWarnings("rawtypes")
	public Games(String name, String year, Set gamesOfUserses, Set imageses, Set postses) {
		this.name = name;
		this.year = year;
		this.gamesOfUserses = gamesOfUserses;
		this.imageses = imageses;
		this.postses = postses;
	}

	public Integer getGid() {
		return this.gid;
	}

	public void setGid(Integer gid) {
		this.gid = gid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	@SuppressWarnings("rawtypes")
	public Set getGamesOfUserses() {
		return this.gamesOfUserses;
	}

	@SuppressWarnings("rawtypes")
	public void setGamesOfUserses(Set gamesOfUserses) {
		this.gamesOfUserses = gamesOfUserses;
	}

	@SuppressWarnings("rawtypes")
	public Set getImageses() {
		return this.imageses;
	}

	@SuppressWarnings("rawtypes")
	public void setImageses(Set imageses) {
		this.imageses = imageses;
	}

	@SuppressWarnings("rawtypes")
	public Set getPostses() {
		return this.postses;
	}

	@SuppressWarnings("rawtypes")
	public void setPostses(Set postses) {
		this.postses = postses;
	}

}
