package backend.model;
// Generated Oct 13, 2023, 3:35:49 PM by Hibernate Tools 6.1.7.Final

/**
 * GamesOfUsers generated by hbm2java
 */
public class GamesOfUsers implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer guid;
	private Games games;
	private Users users;

	public GamesOfUsers() {
	}

	public GamesOfUsers(Games games, Users users) {
		this.games = games;
		this.users = users;
	}

	public Integer getGuid() {
		return this.guid;
	}

	public void setGuid(Integer guid) {
		this.guid = guid;
	}

	public Games getGames() {
		return this.games;
	}

	public void setGames(Games games) {
		this.games = games;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
