package backend.model;
// Generated Sep 10, 2023, 2:06:15 PM by Hibernate Tools 6.1.7.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Games generated by hbm2java
 */

@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@SuppressWarnings("rawtypes")
public class Games implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer gid;
	private String name;
	private String year;
	@JsonIgnore private Set gamesOfUserses = new HashSet(0);
	@JsonIgnore private Set imageses = new HashSet(0);
	@JsonIgnore private Set postses = new HashSet(0);

	public Games() {
	}

	public Games(String name, String year) {
		this.name = name;
		this.year = year;
	}

	public Games(String name, String year, Set gamesOfUserses, Set imageses, Set postses) {
		this.name = name;
		this.year = year;
		this.gamesOfUserses = gamesOfUserses;
		this.imageses = imageses;
		this.postses = postses;
	}

	public Integer getGid() {
		return this.gid;
	}

	public void setGid(Integer gid) {
		this.gid = gid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public Set getGamesOfUserses() {
		return this.gamesOfUserses;
	}

	public void setGamesOfUserses(Set gamesOfUserses) {
		this.gamesOfUserses = gamesOfUserses;
	}

	public Set getImageses() {
		return this.imageses;
	}

	public void setImageses(Set imageses) {
		this.imageses = imageses;
	}

	public Set getPostses() {
		return this.postses;
	}

	public void setPostses(Set postses) {
		this.postses = postses;
	}

}
