package backend.model;

// Generated Oct 6, 2023, 8:07:22 PM by Hibernate Tools 6.1.7.Final

/**
 * Images generated by hbm2java
 */
public class Images implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer iid;
	private Games games;
	private Posts posts;
	private Comments comments;
	private Users users;
	private String path;

	public Images() {
	}

	public Images(Users users, String path) {
		super();
		this.users = users;
		this.path = path;
	}

	public Images(Comments comments, String path) {
		super();
		this.comments = comments;
		this.path = path;
	}

	public Images(Posts posts, String path) {
		super();
		this.posts = posts;
		this.path = path;
	}

	public Images(Games games, String path) {
		super();
		this.games = games;
		this.path = path;
	}

	public Images(Games games, Posts posts, Comments comments, Users users, String path) {
		this.games = games;
		this.posts = posts;
		this.comments = comments;
		this.users = users;
		this.path = path;
	}

	public Integer getIid() {
		return this.iid;
	}

	public void setIid(Integer iid) {
		this.iid = iid;
	}

	public Games getGames() {
		return this.games;
	}

	public void setGames(Games games) {
		this.games = games;
	}

	public Posts getPosts() {
		return this.posts;
	}

	public void setPosts(Posts posts) {
		this.posts = posts;
	}

	public Comments getComments() {
		return this.comments;
	}

	public void setComments(Comments comments) {
		this.comments = comments;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

}
