package backend.model;
// Generated Aug 9, 2023, 10:00:26 PM by Hibernate Tools 6.1.7.Final

/**
 * LoginAttempts generated by hbm2java
 */
public class LoginAttempts implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String ipAddress;
	private String login;
	private Integer time;

	public LoginAttempts() {
	}

	public LoginAttempts(String login) {
		this.login = login;
	}

	public LoginAttempts(String ipAddress, String login, Integer time) {
		this.ipAddress = ipAddress;
		this.login = login;
		this.time = time;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public Integer getTime() {
		return this.time;
	}

	public void setTime(Integer time) {
		this.time = time;
	}

}
