package backend.model;
// Generated Oct 6, 2023, 8:07:22 PM by Hibernate Tools 6.1.7.Final

/**
 * ReportedPosts generated by hbm2java
 */
public class ReportedPosts implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer rpid;
	private Posts posts;
	private Users users;
	private String reason;
	private String status;

	public ReportedPosts() {
	}

	public ReportedPosts(Posts posts, Users users, String reason, String status) {
		this.posts = posts;
		this.users = users;
		this.reason = reason;
		this.status = status;
	}

	public Integer getRpid() {
		return this.rpid;
	}

	public void setRpid(Integer rpid) {
		this.rpid = rpid;
	}

	public Posts getPosts() {
		return this.posts;
	}

	public void setPosts(Posts posts) {
		this.posts = posts;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
