package backend.model;
// Generated Oct 6, 2023, 8:07:22 PM by Hibernate Tools 6.1.7.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer uid;
	private String email;
	private String password;
	private String username;
	private String name;
	private String surname;
	private String roll;
	private String status;
	private Timestamp lastLogin;
	private Timestamp createAt;
	@SuppressWarnings("rawtypes")
	private Set gamesOfUserses = new HashSet(0);
	@SuppressWarnings("rawtypes")
	private Set requestedGameses = new HashSet(0);
	@SuppressWarnings("rawtypes")
	private Set postses = new HashSet(0);
	@SuppressWarnings("rawtypes")
	private Set reportedPostses = new HashSet(0);
	@SuppressWarnings("rawtypes")
	private Set imageses = new HashSet(0);
	@SuppressWarnings("rawtypes")
	private Set commentses = new HashSet(0);
	@SuppressWarnings("rawtypes")
	private Set likeds = new HashSet(0);

	public Users() {
	}

	public Users(String email, String password, String username, String name, String surname, String roll,
			String status, Timestamp createAt) {
		this.email = email;
		this.password = password;
		this.username = username;
		this.name = name;
		this.surname = surname;
		this.roll = roll;
		this.status = status;
		this.createAt = createAt;
	}

	@SuppressWarnings("rawtypes")
	public Users(String email, String password, String username, String name, String surname, String roll,
			String status, Timestamp lastLogin, Timestamp createAt, Set gamesOfUserses, Set requestedGameses,
			Set postses, Set reportedPostses, Set imageses, Set commentses, Set likeds) {
		this.email = email;
		this.password = password;
		this.username = username;
		this.name = name;
		this.surname = surname;
		this.roll = roll;
		this.status = status;
		this.lastLogin = lastLogin;
		this.createAt = createAt;
		this.gamesOfUserses = gamesOfUserses;
		this.requestedGameses = requestedGameses;
		this.postses = postses;
		this.reportedPostses = reportedPostses;
		this.imageses = imageses;
		this.commentses = commentses;
		this.likeds = likeds;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getRoll() {
		return this.roll;
	}

	public void setRoll(String roll) {
		this.roll = roll;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Timestamp getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(Timestamp lastLogin) {
		this.lastLogin = lastLogin;
	}

	public Timestamp getCreateAt() {
		return this.createAt;
	}

	public void setCreateAt(Timestamp createAt) {
		this.createAt = createAt;
	}

	@SuppressWarnings("rawtypes")
	public Set getGamesOfUserses() {
		return this.gamesOfUserses;
	}

	@SuppressWarnings("rawtypes")
	public void setGamesOfUserses(Set gamesOfUserses) {
		this.gamesOfUserses = gamesOfUserses;
	}

	@SuppressWarnings("rawtypes")
	public Set getRequestedGameses() {
		return this.requestedGameses;
	}

	@SuppressWarnings("rawtypes")
	public void setRequestedGameses(Set requestedGameses) {
		this.requestedGameses = requestedGameses;
	}
	
	@SuppressWarnings("rawtypes")
	public Set getPostses() {
		return this.postses;
	}

	@SuppressWarnings("rawtypes")
	public void setPostses(Set postses) {
		this.postses = postses;
	}

	@SuppressWarnings("rawtypes")
	public Set getReportedPostses() {
		return this.reportedPostses;
	}

	@SuppressWarnings("rawtypes")
	public void setReportedPostses(Set reportedPostses) {
		this.reportedPostses = reportedPostses;
	}

	@SuppressWarnings("rawtypes")
	public Set getImageses() {
		return this.imageses;
	}

	@SuppressWarnings("rawtypes")
	public void setImageses(Set imageses) {
		this.imageses = imageses;
	}

	@SuppressWarnings("rawtypes")
	public Set getCommentses() {
		return this.commentses;
	}

	@SuppressWarnings("rawtypes")
	public void setCommentses(Set commentses) {
		this.commentses = commentses;
	}

	@SuppressWarnings("rawtypes")
	public Set getLikeds() {
		return this.likeds;
	}

	@SuppressWarnings("rawtypes")
	public void setLikeds(Set likeds) {
		this.likeds = likeds;
	}

}
